modules/pyramid/models/Node.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\models;

use app\helpers\Account;
use app\models\User;
use Exception;
use Yii;
use yii\db\ActiveRecord;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * This is the model class for table "node".
 *
 * @property integer $id
 * @property string $user_name
 * @property integer $type_id
 * @property integer $count
 * @property integer $time
 *
 * @property Type $type
 * @property User $user
 * @property Node[] $children
 */
class Node extends ActiveRecord
{
    private $_children;

    public static function tableName() {
        return 'node';
    }

    public function rules() {
        return [
            [['user_name', 'type_id', 'count', 'time'], 'required'],
            [['type_id', 'count', 'time'], 'integer', 'min' => 0],
            [['user_name'], 'string', 'max' => 24],
            ['time', 'default', 'value' => $_SERVER['REQUEST_TIME']]
        ];
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_name' => Yii::t('app', 'Username'),
            'type_id' => Yii::t('app', 'Plan'),
            'count' => Yii::t('app', 'Counter'),
            'time' => Yii::t('app', 'Time'),
        ];
    }

    /**
     * @return User
     */
    public function getUser() {
        return $this->hasOne(User::class, ['name' => 'user_name']);
    }

    public function setUser(User $value) {
        $this->user_name = $value->name;
    }

    /**
     * @return Type
     */
    public function getType() {
        return $this->hasOne(Type::class, ['id' => 'type_id']);
    }

    public function setType(Type $value) {
        $this->type_id = $value->id;
    }

    public function getChildren() {
        if (!$this->_children) {
            $this->_children = Node::find()->where(['>', 'id', $this->id])->limit(40)->all();
        }
        return $this->_children;
    }

    public function countQueue() {
        return static::find()
            ->andWhere('time <= :time', [':time' => $this->time])
            ->andWhere(['type_id' => $this->type_id])
            ->sum('count');
    }

    public function decrement() {
        $this->count--;
        return $this->update(false, ['count']);
    }

    public function invest() {
        $this->count = $this->type->degree;
        $this->time = $_SERVER['REQUEST_TIME'];
        if ($expectant = $this->getExpectant($this->type_id)) {
            if ($expectant->count > 1) {
                $expectant->decrement();
            } else {
                $user = $expectant->user;
                $expectant->delete();
                Income::make($expectant);
                Account::add('profit', $this->type->profit);
                $user->account += (float) $this->type->getIncomeWithoutReinvest();
                if ($user->update(false, ['account'])) {
                    $expectant->invest();
                } else {
                    throw new Exception($this->dump());
                }
            }
        }
        if ($this->save()) {
            return true;
        }
        return false;
    }

    /**
     * @param $type_id
     * @return Node
     */
    public function getExpectant($type_id) {
        return static::find()->where(['type_id' => $type_id])->andWhere('count > 0')
            ->orderBy(['time' => SORT_ASC, 'id' => SORT_ASC])->limit(1)->one();
    }

    public function dump() {
        $bundle = [
            'id' => $this->id,
            'type_id' => $this->type_id,
            'count' => $this->count,
            'time' => date($this->time),
            'user_name' => $this->user_name,
            'account' => $this->user->account
        ];
        if (count($this->errors) > 0) {
            $bundle['errors'] = $this->errors;
        }
        if (count($this->user->errors) > 0) {
            $bundle['user_errors'] = $this->user->errors;
        }
        return json_encode($bundle, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }

    public function __toString() {
        return $this->id . ' ' . Type::get($this->type_id);
    }
}

modules/pyramid/controllers/NodeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\controllers;


use app\behaviors\Access;
use app\helpers\SQL;
use app\modules\pyramid\models\Matrix;
use app\modules\pyramid\models\Node;
use app\modules\pyramid\models\Type;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class NodeController extends Controller
{
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::class,
                'manager' => ['create', 'update', 'delete']
            ],

            'cache' => [
                'class' => 'yii\filters\HttpCache',
                'cacheControlHeader' => 'must-revalidate, private',
                'only' => ['index', 'matrix'],
                'enabled' => true,
                'lastModified' => function ($action, $params) {
                    $query = Node::find();
                    if (isset($params['user'])) {
                        $query->where(['user_name' => $params['user']]);
                    }

                    if (isset($params['id'])) {
                        $query->where(['type_id' => (int) SQL::queryCell('SELECT type_id FROM node WHERE id = :id', [
                            ':id' => (int) $params['id']
                        ])]);
                    }

                    return (int) $query->max('time');
                },
            ]
        ];
    }

    public function actionIndex($user = null, $id = null) {
        $parent = $id ? $this->findModel($id) : null;
        $query = Node::find()
            ->with('type');
        if ($user) {
            $query->andWhere(['user_name' => $user]);
        }
        elseif ($parent) {
            $query
                ->andWhere('"time" < :time', [':time' => $parent->time])
                ->andWhere(['type_id' => $parent->type_id]);
        }
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => $query,
                'sort' => [
                    'defaultOrder' => [
                        'time' => SORT_DESC,
                        'id' => SORT_DESC,
                    ]
                ]
            ]),
            'parent' => $parent
        ]);
    }

    public function actionCreate($id = null) {
        $model = new Node();
        if ($id) {
            $base = $this->findModel($id);
            $model->time = $base->time - 1;
            $model->type_id = $base->type_id;
        }
        else {
            $model->time = time();
        }

        $is_post = $model->load(Yii::$app->request->post());
        if ($is_post) {
            $model->count = $model->type->degree;
            if ($is_post && $model->validate()) {
                if ($model->save(false)) {
                    return $this->redirect(['invest', 'id' => $model->id]);
                }
            }
            else {
                Yii::$app->session->setFlash('error', json_encode($model->errors, JSON_UNESCAPED_UNICODE));
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['invest', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionMatrix($page = 1, $size = 15, $order = 'asc') {
        if ((Yii::$app->user->isGuest || !Yii::$app->user->identity->isManager()) && $size > 100) {
            return $this->redirect(['index', 'size' => 15]);
        }

        $count = Matrix::find()->select('count(*) as "count"')->groupBy('type_id')->column();
        $count = empty($count) ? 0 : (int) max($count);

        $pages = [
            'totalCount' => $count,
            'pageSize' => $size,
            'pageSizeParam' => 'size',
            'page' => $page - 1
        ];

        $pages = new Pagination($pages);

        /** @var \yii\db\Query $query */
        $query = null;
        $order = 'desc' == $order ? SORT_DESC : SORT_ASC;
        $table = [];
        foreach(Type::all() as $type) {
            $table[] = Matrix::find()
                ->where(['type_id' => $type->id])
                ->offset($pages->offset)
                ->limit($pages->limit)
                ->orderBy(['time' => $order, 'id' => $order])
                ->all();
        }

        return $this->render('matrix', [
            'models' => $table,
            'pages' => $pages,
            'order' => $order
        ]);
    }

    /**
     * Finds the Type model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Node the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Node::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/pyramid/controllers/TypeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\controllers;


use app\modules\pyramid\models\Node;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\modules\pyramid\models\Type;
use yii\web\NotFoundHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class TypeController extends Controller {
/*
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'open' => ['post'],
                ]
            ]
        ];
    }
*/
    public function actionIndex() {
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => Type::find(),
                'sort' => [
                    'defaultOrder' => ['id' => SORT_ASC]
                ]
            ]),
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionOpen($id) {
        $node = new Node([
            'type' => $this->findModel($id),
            'user' => Yii::$app->user->identity
        ]);

        if ($node->type->isSpecial() && !$node->user->isTeam()) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'You are not in team to open this plan'));
        }
        elseif ($node->user->account >= $node->type->stake) {
            $node->user->account -= $node->type->stake;
            $transaction = Yii::$app->db->beginTransaction();
            try {
                if ($node->user->update(true, ['account']) && $node->invest()) {
                    $transaction->commit();
                    Yii::$app->session->setFlash('success', Yii::t('app', 'The plan is open'));
                }
            }
            catch(\Exception $ex) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', $ex->getMessage());
            }
        }
        else {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Insufficient funds'));
            return $this->redirect(['view', 'id' => $node->id]);
        }

        return $this->redirect(['view', 'id' => $id]);
    }

    /**
     * Finds the Type model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Type the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Type::get($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/pyramid/views/node/_form.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\models\Type;
use app\widgets\AjaxComplete;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Node */
/* @var $form yii\widgets\ActiveForm */

$types = Type::getItems();
?>

<div class="type-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_name')->widget(AjaxComplete::class, [
        'route' => ['user/complete']
    ]) ?>
    <?= $form->field($model, 'type_id')->dropDownList($types) ?>
    <?php
    if (!$model->isNewRecord) {
        echo $form->field($model, 'count');
    }
    ?>
    <?php
    array_unshift($types, Yii::t('app', 'Investment'), 0);
    unset($types[1]);
    echo $form->field($model, 'reinvest_from')->dropDownList($types);
    echo Html::activeHiddenInput($model, 'time');
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord
            ? Yii::t('app', 'Create')
            : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/pyramid/views/node/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Type */

$this->title = Yii::t('app', 'Create Investment');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Queue'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="type-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/pyramid/views/node/index.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\modules\pyramid\models\Node;
use app\widgets\Ext;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View
 * @var $parent Node
 * @var $dataProvider yii\data\ActiveDataProvider
 */

$user = isset($_GET['user']) ? $_GET['user'] : null;
$mine = !Yii::$app->user->isGuest && (Yii::$app->user->identity->isManager() || Yii::$app->user->identity->name == $user);
$title = $this->title = Yii::t('app', 'Investments');
$columns = [
    'id',
    [
        'attribute' => 'user_name',
        'format' => 'html',
        'value' => function($model) {
            return Html::a($model->user_name, ['/user/view', 'name' => $model->user_name]);
        }
    ],
    'time:datetime',
    [
        'label' => Yii::t('app', 'Action'),
        'format' => 'html',
        'value' => function($model) {
            return Html::a(Yii::t('app', 'View'), ['index', 'id' => $model->id],
                ['class' => 'btn btn-primary btn-xs']);
        }
    ]
];


if (isset($parent)) {
    $title = $parent->type->name . " #$parent->id ";
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Investments'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $title;
    $this->title = $title;
    $title .= $mine ? Html::a($parent->user_name, ['/user/view', 'name' => $parent->user_name]) : $parent->user_name;

}
else {
    $additional = [$columns[0],
        [
            'attribute' => 'type_id',
            'label' => Yii::t('app', 'Plan'),
            'format' => 'html',
            'value' => function($model) {
                return Html::a($model->type->name, ['type/view', 'id' => $model->type_id]);
            }
        ]
    ];
    if ($user) {
        $this->title = Yii::t('app', 'Investments of user') . ' ' . $user;
        if ($mine) {
            $title = Yii::t('app', 'Investments of user') . ' ' . Html::a($user, ['/user/view', 'name' => $user]);
        }
        else {
            $title = $this->title;
        }
        $additional[] = [
            'attribute' => 'time',
            'label' => Yii::t('app', 'Remains to exit'),
            'value' => function(Node $model) {
                return $model->countQueue();
            }

        ];
    }
    $columns = array_merge($additional, array_slice($columns, 1));
}

?>
<div class="invest">
    <?= Ext::stamp() ?>
    <div>
        <h1><?= $title ?></h1>

        <div class="form-group">
            <?php
            if (isset($parent)) {
                if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
                    echo implode(' ', [
                        Html::a(Yii::t('app', 'Update'), ['update', 'id' => $parent->id], ['class' => 'btn btn-primary']),
                        Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $parent->id], ['class' => 'btn btn-danger']),
                        Html::a(Yii::t('app', 'Up'), ['up', 'id' => $parent->id], ['class' => 'btn btn-warning'])
                    ]);
                }
            }
            ?>
        </div>

        <?php
        if (isset($parent)) {
            echo Html::tag('p', Yii::t('app', 'Remains to exit') . ': ' . $parent->countQueue());
        }
        ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summary' => '',
        'emptyText' => '',
        'showOnEmpty' => false,
        'columns' => $columns,
    ])
    ?>

</div>

modules/pyramid/views/node/matrix.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\modules\pyramid\models\Type;
use yii\data\ArrayDataProvider;
use yii\grid\SerialColumn;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $models array */
/* @var $pages yii\data\Pagination */
/* @var $order integer */

$this->title = Yii::t('app', 'Queue');

$columns = [[
    'class' => SerialColumn::className(),
    'contentOptions' => ['class' => 'id']
]];
$keys = array_keys($models);

$types = Type::all();
foreach($keys as $i) {
    $columns[] = [
        'attribute' => $i + 1,
        'label' => $types[$i + 1],
        'format' => 'html',
        'contentOptions' => function($row) use ($i) {
            return isset($row[$i]) && !Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()
                ? ['data-id' => $row[$i]['id']]
                : [];
        },
        'value' => function($row) use ($i) {
            if (isset($row[$i])) {
                $invest = $row[$i];
                $cell = Html::a($invest['user_name'], ['index', 'id' => $invest['id']]);
                $count = $invest['count'];
                if ($count > 1) {
                    $cell .= " <span class='count'>$count</span>";
                }
                return $cell;
            }
            else {
                return '';
            }
        }
    ];
}

$transposed = [];
$types_length = count($types);
foreach($models as $i => $column) {
    foreach($column as $j => $cell) {
        if (empty($transposed[$j])) {
            $transposed[$j] = [];
        }
        $transposed[$j][$i] = $cell;
    }
}

?>
<div class="matrix">
    <div class="control">
        <?php
        $links = [Html::tag('label', Yii::t('app', 'Page size') . ':')];
        $page_list = [15, 25, 50, 100, 250, 500, 1000];
        foreach($page_list as $size) {
            $links[] = ($size == $pages->pageSize ? $size
                : Html::a($size, ['matrix', 'size' => $size, 'order' => $order ? 'asc' : 'desc'],
                    ['data-role' => $size > 100 ? 'manage' : 'plain']));
        }
        echo Html::tag('script', implode(' ', $links), [
            'type' => 'text/plain',
            'data-selector' => '#page-size'
        ]);

        echo Html::tag('script', implode(' ', [
            Html::tag('label', Yii::t('app', 'show') . ':'),
            SORT_DESC == $order
                ? Html::a(Yii::t('app', 'start of the queue'), ['matrix', 'order' => 'asc', 'size' => $pages->pageSize])
                : Html::a(Yii::t('app', 'end of queue'), ['matrix', 'order' => 'desc', 'size' => $pages->pageSize])
        ]), [
            'type' => 'text/plain',
            'data-selector' => '#sort-order'
        ]);
        ?>
        <p>
            <span id="page-size"></span>
            <span id="sort-order"></span>
        </p>

        <?php
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
            echo Html::tag('div', Html::a(Yii::t('app', 'Create'), ['create'], ['class' => 'btn btn-success']),
                ['class' => 'form-group']);
        }
        ?>

        <?= LinkPager::widget([
            'pagination' => $pages,
        ]); ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => new ArrayDataProvider([
            'allModels' => $transposed,
            'pagination' => false,
            'sort' => false
        ]),
        'columns' => $columns
    ]); ?>

</div>

modules/pyramid/views/node/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Type */

$this->title = Yii::t('app', 'Update');
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['invest', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="type-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/pyramid/views/node/view.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Node */

$this->title = $model->type->name . " #$model->id";
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Queue'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Investment'), 'url' => ['invest']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="type-view">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>

    <div id="matrix">
        <h2><?= count($model->children) ?> из <?= $model->type->degree ?></h2>
        <?php
        foreach($model->children as $child) {
            echo Html::a($child->user_name, ['/user/view', 'name' => $child->user_name]);
        }
        ?>
    </div>
</div>